[[manager.prepend_keymap]]
on   = [ "t" ]
run  = 'open'
desc = "open file"
[[manager.prepend_keymap]]
on   = [ "e" ]
run  = 'open'
desc = "open file"

[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "close"
desc = "Cancel input"
[[manager.prepend_keymap]]
on   = [ "l" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"
