[[manager.prepend_keymap]]
on   = [ "t" ]
run  = 'open'
desc = "open file"
[[manager.prepend_keymap]]
on   = [ "e" ]
run  = 'open'
desc = "open file"

[[manager.prepend_keymap]]
on   = [ "R" ]
run  = 'rename --cursor=start'
desc = "rename file from start"

[[manager.prepend_keymap]]
on   = [ "<Space>", "r" ]
run  = 'rename --empty=stem --cursor=start'
desc = "rename file from scratch with saved extension"

[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "close"
desc = "Cancel input"
[[manager.prepend_keymap]]
on   = [ "l" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"


# bookmark plugin
[[manager.prepend_keymap]]
on = [ "<Space>", "a" ]
run = "plugin bookmarks --args='save'"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = [ "<Space>", "g" ]
run = "plugin bookmarks --args='jump'"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = [ "<Space>", "d" ]
run = "plugin bookmarks --args='delete'"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = [ "<Space>", "D" ]
run = "plugin bookmarks --args='delete_all'"
desc = "Delete all bookmarks"

[[manager.prepend_keymap]]
on = [ "<Space>", "m" ]
run = "plugin bookmarks --args='modify'"
desc = "modify key bind to hoverd path"

